services:
  caddy:
    container_name: caddy
    image: ankit/caddy-cloudflare:0.1
    restart: unless-stopped
    entrypoint: ["caddy", "run", "--watch", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
    environment:
      - TZ=America/Vancouver
      - CLOUDFLARE_TOKEN=${CLOUDFLARE_TOKEN}
      - DEPLOY_DOMAIN=${DEPLOY_DOMAIN}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - ./docker-data/caddy/data:/data
      - ./docker-data/caddy/config:/config
    networks: ["web"]

  whoami:
    container_name: whoami
    image: traefik/whoami
    restart: unless-stopped
    networks: ["web"]

  actual_server1:
    container_name: actualbudget
    image: docker.io/actualbudget/actual-server:latest
    restart: unless-stopped
    environment:
      - TZ=America/Vancouver
      # Uncomment any of the lines below to set configuration options.
      # - ACTUAL_HTTPS_KEY=/data/selfhost.key
      # - ACTUAL_HTTPS_CERT=/data/selfhost.crt
      - ACTUAL_PORT=80
      # - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      # - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      # - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
      # See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration
      # !! If you are not using any of these options, remove the 'environment:' tag entirely.
    volumes:
      # Change './actual-data' below to the path to the folder you want Actual to store its data in on your server.
      # '/data' is the path Actual will look for its files in by default, so leave that as-is.
      - ./docker-data/actual-budget/data:/data
    networks: ["web"]

networks:
  web:
    name: web
